- name: Add Clients to the domain 
  hosts: Client
  vars_files: 
    - ./vars/creds.yaml
    - ./vars/vars.yaml


  tasks: 
  - name: add to domain
    win_domain_membership: 
      domain_admin_user: "{{ domain_admin }}"
      domain_admin_password : "{{domain_admin_pass}}"
      dns_domain_name: "{{ domain_name }}"
      state: domain
    register: domain_state  
  - ansible.windows.win_reboot:
    when: domain_state.reboot_required
