- name: Set up DC
  hosts: DC
  vars_files:
    - /vars/creds.yaml

  

  tasks:
  - name: Create a domain
    win_domain:
      dns_domain_name: "{{ domain_name }}"
      install_dns: true # by default
      safe_mode_password: "{{SafeModePass}}"
    register: domain_install
  - name: reboot after creating the domain
    win_reboot: ()
    when: domain_install.reboot_required


  - name: Promote the server to DC    
    win_domain_controller:
      dns_domain_name: "{{domain_name}}"
      domain_admin_user: "{{domain_admin}}"
      domain_admin_password: "{{domain_admin_pass}}"
      state: domain_controller
    register: to_dc

  - name: reboot after promotion
    win_reboot: ()
    when: to_dc.reboot_required

  